'use client';
import { FormEvent, useState } from 'react';
import { scoreLead } from '@/lib/scoreLead';

const initial = { firstName:'',lastName:'',email:'',phone:'',city:'',department:'',localStatus:'En recherche',format:'Je ne sais pas encore',personalContribution:'',estimatedBudget:'',hasRestaurantExperience:'Non',hasEntrepreneurExperience:'Non',openingTimeline:'6-12 mois',operatorModel:'Oui',motivation:'',message:'',rgpd:false };

export default function LeadForm(){const [form,setForm]=useState(initial); const [errors,setErrors]=useState<string[]>([]); const [ok,setOk]=useState(false);
const submit=(e:FormEvent)=>{e.preventDefault();const err=[] as string[]; if(!form.firstName)err.push('Prénom'); if(!form.lastName)err.push('Nom'); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))err.push('Email valide'); if(!form.phone)err.push('Téléphone'); if(!form.city)err.push('Ville'); if(!form.personalContribution)err.push('Apport'); if(!form.rgpd)err.push('RGPD'); setErrors(err); if(err.length) return; scoreLead({city:form.city, personalContribution:form.personalContribution, hasRestaurantExperience:form.hasRestaurantExperience as 'Oui'|'Non', hasEntrepreneurExperience:form.hasEntrepreneurExperience as 'Oui'|'Non', openingTimeline:form.openingTimeline as any, localStatus:form.localStatus as any, motivation:form.motivation}); setOk(true); setForm(initial);};
const update=(k:string,v:string|boolean)=>setForm((p)=>({...p,[k]:v}));
return <section id='eligibilite' className='section'><h2 className='text-3xl font-bold'>Testez votre éligibilité pour ouvrir une Pizza Zio</h2>{errors.length>0&&<p className='mt-3 text-sm text-red-700'>Merci de compléter : {errors.join(', ')}.</p>}{ok&&<p className='mt-3 rounded-xl bg-green-100 p-3 text-green-900'>Merci pour votre demande. Votre projet va être étudié par l’équipe Pizza Zio. Si votre profil correspond aux critères actuels de développement du réseau, vous serez recontacté prochainement.</p>}<form onSubmit={submit} className='mt-6 grid gap-4 md:grid-cols-2'>{[['firstName','Prénom'],['lastName','Nom'],['email','Email'],['phone','Téléphone'],['city','Ville ciblée'],['department','Département'],['personalContribution','Apport personnel disponible'],['estimatedBudget','Budget total estimé']].map(([k,l])=><input key={k} className='rounded-xl border p-3' placeholder={l} value={(form as any)[k]} onChange={(e)=>update(k,e.target.value)} />)}<textarea className='rounded-xl border p-3 md:col-span-2' placeholder='Pourquoi souhaitez-vous rejoindre Pizza Zio ?' value={form.motivation} onChange={(e)=>update('motivation',e.target.value)} /><textarea className='rounded-xl border p-3 md:col-span-2' placeholder='Message libre' value={form.message} onChange={(e)=>update('message',e.target.value)} /><label className='md:col-span-2'><input type='checkbox' checked={form.rgpd} onChange={(e)=>update('rgpd',e.target.checked)} /> J’accepte que mes données soient utilisées pour être recontacté.</label><button className='cta md:col-span-2 w-fit' type='submit'>Envoyer ma candidature</button></form></section>}
